### ISSUE TITLE
Issue with old version of composer/composer

### ISSUE THREAD

**Issue by jorgehs91** [genecommerce/module-encryption-key-manager#14]
Hi guys,
Any chance to replace the following imported namespace?
https://github.com/genecommerce/module-encryption-key-manager/blob/7b9e50e9562c63645acb2f7ecc09ea0f4853b0f0/Console/ReencryptColumn.php#L5
Older versions of `composer/composer` doesn't have this class (below version `2.4.0`). I believe this class could be used instead: `\Symfony\Component\Console\Input\InputArgument`

**Comment by convenient** [comment]
Any chance you can raise a PR?

I must have accepted the suggested one in phpstorm and not spotted it, I definitely intended to use symphony console

**Comment by convenient** [comment]
https://github.com/genecommerce/module-encryption-key-manager/releases/tag/v0.0.5-alpha

**Comment by convenient** [comment]
Thanks for the contribution @jorgehs91
