### ISSUE TITLE
Add package to Packagist?

### ISSUE THREAD

**Issue by jantzenw** [genecommerce/module-encryption-key-manager#17]
Hi!

Would it make sense to add this module to Packagist, perhaps alongside other gene modules? https://packagist.org/packages/gene/

Reasoning: This might be helpful in allowing users to require this package without adding this particular repository as a package source.

Thank you!

**Comment by convenient** [comment]
Work is in progress on this front 👍

**Comment by convenient** [comment]
Thanks https://packagist.org/packages/gene/module-encryption-key-manager
