### ISSUE TITLE
Production Site, cant generate new key

### ISSUE THREAD

**Issue by plunagariya** [genecommerce/module-encryption-key-manager#33]
Hi, 
I want to use this key-generator, and I tested it on my local and stagging store. Here it working as expected. So I have decided to use it on production, but at production I am getting error like **There are no commands defined in the "gene:encryption-key-manager" namespace.** 

Steps I followed are:
composer require gene/module-encryption-key-manager:dev-master
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:st:deploy
bin/magento gene:encryption-key-manager:generate --force

At this stage, I am getting the above error message. Can you suggest to me what I need to do here, or where I am wrong?

**Comment by convenient** [comment]
Hello

1. When you run `php bin/magento` do you get any errors at the bottom?
2. What is the output of `composer info gene/module-encryption-key-manager` ? I see you are requiring `dev-master` which is a moving target. I appreciate the current tags are all alpha version, but using a tag will be more stable and consistent.
3. When you look in `php bin/magento module:status` can you see `Gene_EncryptionKeyManager`

**Comment by plunagariya** [comment]
Hi again @convenient 

Thank you, for your reply, I tried with v9-alpha version, and is worked. So I think it was my mistake by dev-master version.
