### ISSUE TITLE
System core_config_data path not correct

### ISSUE THREAD

**Issue by JoostWan** [genecommerce/module-encryption-key-manager#35]
`system/default/dev/debug/gene_encryption_manager_only_log_old_decrypts`

https://github.com/genecommerce/module-encryption-key-manager/blob/master/Plugin/LogDecrypts.php#L40

Must be  `dev/debug/gene_encryption_manager_only_log_old_decrypts `

Same for https://github.com/genecommerce/module-encryption-key-manager/blob/master/Plugin/LogDecrypts.php#L36

https://github.com/genecommerce/module-encryption-key-manager/blob/master/etc/adminhtml/system.xml

**Comment by convenient** [comment]
Hey @JoostWan , is this all working okay for you then?

**Comment by JoostWan** [comment]
@convenient Sorry, mistake on our side. We missed the function for adding the values to the env.php. The first one doesn’t work when maintenance is disabled because of the extensive logging (We think). When you run the second command first and then enabled the logging its working fine. 

Many thanks for this module :)

**Comment by convenient** [comment]
I will update the docs to ensure they're activated in the correct order
