### ISSUE TITLE
Problem when running php bin/magento gene:encryption-key-manager:generate --force

### ISSUE THREAD

**Issue by realadityayadav** [genecommerce/module-encryption-key-manager#40]
Gene\EncryptionKeyManager\Service\ReencryptEnvSystemConfigurationValues::iterateSystemConfig(): Argument #1 ($systemConfig) must be of type array, null given, called in app/code/Gene/EncryptionKeyManager/Service/ReencryptEnvSystemConfigurationValues.php on line 49

This was working before yesterday.

**Comment by convenient** [comment]
Hello @realadityayadav 

Is this on your local, I expect this patch will work ? https://github.com/genecommerce/module-encryption-key-manager/pull/42

**Comment by convenient** [comment]
did that help @realadityayadav ?

**Comment by realadityayadav** [comment]
Yes it worked.
