### ISSUE TITLE
The "--key" option does not exist.

### ISSUE THREAD

**Issue by lima195** [genecommerce/module-encryption-key-manager#50]
Hi,

I'm trying to generate passing the key param like it's mentioned in the documentation (readme.md), but I get this error:

```
bin/magento gene:encryption-key-manager:generate --key=sdgh214h21l23b5l32blhoafslsabEXAMPLE;
```

> The "--key" option does not exist.  

Package Version:
```
v0.0.8-alpha
```

Thanks

**Comment by convenient** [comment]
Hello

https://github.com/genecommerce/module-encryption-key-manager/releases/tag/v0.0.9-alpha

Version 0.0.9 alpha and higher has that flag
