### ISSUE TITLE
Is it only possible to re-encrypt the "General" customer group ?

### ISSUE THREAD

**Issue by hgati** [genecommerce/module-encryption-key-manager#60]
Only customers belonging to the "General" customer group were re-encrypted, not all customer.
Can it be applied to other customer groups as well ?

![image](https://github.com/user-attachments/assets/5c7649c1-ebe8-4e4a-ba3a-2a336c42a49d)

![image](https://github.com/user-attachments/assets/4db52061-f340-4b39-8028-4f1b5b0a5605)

**Comment by convenient** [comment]
https://github.com/genecommerce/module-encryption-key-manager/blob/97ae562a42d03474c725ae39cab56f39cb4be6d3/Console/ReencryptColumn.php#L133-L141

This should grab all rows from the table with a column matching the encrypted data format.

Did you figure out the issue?

**Comment by hgati** [comment]
@convenient I found out that it's not about the customer group, but rather the issue occurs when the value of the `rp_token` field in the database is stored as NULL. so it doesn't seem to be an issue.

Before
```sql
SELECT `cb_customer_entity`.`entity_id`, `cb_customer_entity`.`rp_token` 
FROM `cb_customer_entity` 
ORDER BY entity_id ASC 
LIMIT 10 
```
![image](https://github.com/user-attachments/assets/d9d33b43-8ad0-4627-a36c-6af661ab7934)


If print the SQL of the code you provided, it looks like the following:
```sql
SELECT `cb_customer_entity`.`entity_id`, `cb_customer_entity`.`rp_token` 
FROM `cb_customer_entity` 
WHERE 
	((`cb_customer_entity`.`rp_token` LIKE '_:_:____%' OR `cb_customer_entity`.`rp_token` LIKE '__:_:____%')) 
	AND 
	(`cb_customer_entity`.`rp_token` NOT LIKE '1:_:__%')
```
![image](https://github.com/user-attachments/assets/b481d909-9b14-4c4a-a28d-0ddd8e7adc24)
